### PR TITLE
Added Rock Paper Scissor Game Based On Javascript

### PR DESCRIPTION
**Pull request by awaneeshsoni**
Hi, 
I am Awaneesh Soni.
I am new to open source.
I have a new project based on simple javascript.
It would be great for me if you could please merge it.

### CODE REVIEW

**Comment by Lynch23** [comment]
Hello Awaneesh, I have reviewed your project, I am about to merge it. Great contribution and happy coding.

**Comment by awaneeshsoni** [comment]
Hi,
Thank you for your email,
Please add Hacktoberfest Topic to it. Otherwise, it will not be counted as
Hacktoberfest Contribution.

**Comment by Lynch23** [comment]
I'd love if you added documentation to your project. That will hep other contributors understand what you built.

**Comment by awaneeshsoni** [comment]
Sorry, the above mail was not written for you.
Thanks and regards.

**Pull request merged**
