### PR TITLE
second commit

### PR DESCRIPTION
**Pull request by lilmeezyd**

### CODE REVIEW

**Comment by Lynch23** [comment]
Hello Dennis, I have reviewed your contribution sorry I took this long, I will go ahead and merge your PR, thank you for such a huge contribution on Arrays

**Comment by Lynch23** [comment]
If you can also share the same contribution to the remake of this repo, you will find the link on the first line of the README markdown of this repository. As this repo no longer participates in the hacktoberfest event.

**Comment by lilmeezyd** [comment]
is it okay if i do contribute more to your repo?

**Comment by Lynch23** [comment]
Yes of course, I'd love that

**Comment by lilmeezyd** [comment]
Okay 👌. But if you got any other repos that you're contributing to, would
you be kind enough to share them. JavaScript and React

**Comment by Lynch23** [comment]
Recently I have not actively contributed to any repo, but I have contributed to old repos in the past like "30 days of react" and "30 days of javascript". If I find any repo that I will be interested in, I will surely keep you posted. I hope that helps

**Comment by lilmeezyd** [comment]
ir does. Thanks, man.

**Comment by Lynch23** [comment]
You are welcome

**Pull request merged**
