### PR TITLE
Added a file regarding Functions in JavaScript

### PR DESCRIPTION
**Pull request by isyneha**

### CODE REVIEW

**Comment by Lynch23** [comment]
I have reviewed your contribution, I will go ahead and merge your pull request to the repo. And I am recreating this repo because it has been excluded from the Hacktoberfest event due to some issues, if your check back to this repo, there will be a link provided to the remake in about an hour. Please check back and recontribute (the same contribution you just made) to the remake of this repo to get your badge for Hacktoberfest.

**Comment by isyneha** [comment]
Sure, I will.

**Comment by Lynch23** [comment]
Thank you and I have just updated the readme file with a link to the remake of this repository, you will find the link at the top of the ReadMe documentation, you can now submit your contribution to the new repository. Happy coding!

**Comment by isyneha** [comment]
Awesome, thanks!

**Comment by isyneha** [comment]
Sure

**Pull request merged**
